DROP DATABASE IF EXISTS beerdb;
DROP USER IF EXISTS `beeradmin`@`%`;
CREATE DATABASE IF NOT EXISTS beerdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `beeradmin`@`%` IDENTIFIED WITH caching_sha2_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `beerdb`.* TO `beeradmin`@`%`;